version: '3.8'

services:
  zdatar-web:
    build: .
    container_name: zdatar-landingpage
    restart: always
    ports:
      - "9443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - ssl-generator
    networks:
      - zdatar-network

  ssl-generator:
    image: alpine:latest
    container_name: zdatar-ssl-generator
    volumes:
      - ./ssl:/ssl
      - ./generate-ssl.sh:/generate-ssl.sh:ro
    command: sh /generate-ssl.sh
    networks:
      - zdatar-network

networks:
  zdatar-network:
    driver: bridge

volumes:
  ssl-certs:
